// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4PTU-ZFUShIH7285RWTZ99ivtew34b8',
    appId: '1:43625745033:web:48867e6c3a78e8a5c3d458',
    messagingSenderId: '43625745033',
    projectId: 'flutterfirebase-36df7',
    authDomain: 'flutterfirebase-36df7.firebaseapp.com',
    storageBucket: 'flutterfirebase-36df7.appspot.com',
    measurementId: 'G-YQQGHRT3P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbRgsQCY52pEoXCRYRc7XjWbXHG8AOtQ',
    appId: '1:43625745033:android:f04796ef4322d098c3d458',
    messagingSenderId: '43625745033',
    projectId: 'flutterfirebase-36df7',
    storageBucket: 'flutterfirebase-36df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuF563qe6EJWn31LKVtmPDTyYnNCw9Mg',
    appId: '1:43625745033:ios:08fbee9b470fc716c3d458',
    messagingSenderId: '43625745033',
    projectId: 'flutterfirebase-36df7',
    storageBucket: 'flutterfirebase-36df7.appspot.com',
    androidClientId: '43625745033-48k0qmt0ja70d2hlco58rkuq7crk7ra1.apps.googleusercontent.com',
    iosClientId: '43625745033-7dfcm8cp1nqsbo0edt8nbu727292g0qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventBuddyFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANuF563qe6EJWn31LKVtmPDTyYnNCw9Mg',
    appId: '1:43625745033:ios:08fbee9b470fc716c3d458',
    messagingSenderId: '43625745033',
    projectId: 'flutterfirebase-36df7',
    storageBucket: 'flutterfirebase-36df7.appspot.com',
    androidClientId: '43625745033-48k0qmt0ja70d2hlco58rkuq7crk7ra1.apps.googleusercontent.com',
    iosClientId: '43625745033-7dfcm8cp1nqsbo0edt8nbu727292g0qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventBuddyFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP4PTU-ZFUShIH7285RWTZ99ivtew34b8',
    appId: '1:43625745033:web:6e7a11ed802b754cc3d458',
    messagingSenderId: '43625745033',
    projectId: 'flutterfirebase-36df7',
    authDomain: 'flutterfirebase-36df7.firebaseapp.com',
    storageBucket: 'flutterfirebase-36df7.appspot.com',
    measurementId: 'G-XDWLWW0GNZ',
  );

}